spring.application.name=ecommerce-backend

# Oracle Database
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=ecommerce
spring.datasource.password=bavly123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
logging.level.org.springframework.security=TRACE
# Flyway

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.flyway=DEBUG

jwt.secret=PutAVeryLongRandomSecretKeyHereAtLeast32CharactersLong
jwt.expiration=86400000