CREATE TABLE products (

                          id NUMBER GENERATED BY DEFAULT AS IDENTITY,

                          name VARCHAR2(150) NOT NULL,

                          description VARCHAR2(1000),

                          price NUMBER(10,2) NOT NULL,

                          stock_quantity NUMBER(10) NOT NULL,

                          CONSTRAINT pk_products PRIMARY KEY (id)

);
CREATE TABLE roles (

                       id NUMBER GENERATED BY DEFAULT AS IDENTITY,

                       name VARCHAR2(20) NOT NULL,

                       CONSTRAINT pk_roles PRIMARY KEY (id),

                       CONSTRAINT uk_roles_name UNIQUE (name),

                       CONSTRAINT chk_roles_name
                           CHECK (name IN ('ADMIN', 'USER'))

);
CREATE TABLE users (

                       id NUMBER GENERATED BY DEFAULT AS IDENTITY,

                       username VARCHAR2(50) NOT NULL,

                       email VARCHAR2(100) NOT NULL,

                       password VARCHAR2(255) NOT NULL,

                       first_name VARCHAR2(50) NOT NULL,

                       last_name VARCHAR2(50) NOT NULL,

                       CONSTRAINT pk_users PRIMARY KEY (id),

                       CONSTRAINT uk_users_username UNIQUE (username),

                       CONSTRAINT uk_users_email UNIQUE (email)

);
CREATE TABLE orders (

                        id NUMBER GENERATED BY DEFAULT AS IDENTITY,

                        order_date TIMESTAMP NOT NULL,

                        status VARCHAR2(20) NOT NULL,

                        total_amount NUMBER(10,2) NOT NULL,

                        user_id NUMBER NOT NULL,

                        CONSTRAINT pk_orders PRIMARY KEY (id),

                        CONSTRAINT fk_orders_user
                            FOREIGN KEY (user_id)
                                REFERENCES users(id),

                        CONSTRAINT chk_order_status
                            CHECK (
                                status IN (
                                           'PENDING',
                                           'SHIPPED',
                                           'DELIVERED',
                                           'CANCELLED'
                                    )
                                )

);
CREATE TABLE order_items (

                             id NUMBER GENERATED BY DEFAULT AS IDENTITY,

                             quantity NUMBER(10) NOT NULL,

                             price_at_purchase NUMBER(10,2) NOT NULL,

                             order_id NUMBER NOT NULL,

                             product_id NUMBER NOT NULL,

                             CONSTRAINT pk_order_items PRIMARY KEY (id),

                             CONSTRAINT fk_order_items_order
                                 FOREIGN KEY (order_id)
                                     REFERENCES orders(id),

                             CONSTRAINT fk_order_items_product
                                 FOREIGN KEY (product_id)
                                     REFERENCES products(id)

);
CREATE TABLE user_roles (

                            user_id NUMBER NOT NULL,

                            role_id NUMBER NOT NULL,

                            CONSTRAINT pk_user_roles
                                PRIMARY KEY (user_id, role_id),

                            CONSTRAINT fk_user_roles_user
                                FOREIGN KEY (user_id)
                                    REFERENCES users(id),

                            CONSTRAINT fk_user_roles_role
                                FOREIGN KEY (role_id)
                                    REFERENCES roles(id)

);